### ISSUE TITLE
Github link

### ISSUE THREAD

**Issue by tholman** [tholman/inspiring-online#31]
I'm working on this at the moment. But I guess its important to let everyone know that they can edit/change pages on github. For spelling mistakes, or anything.

**Comment by TJScalzo** [comment]
@tholman, I'm not sure if you want to use it, but I've added one of your [Github Corners](http://tholman.com/github-corners/#) to the site and it looks pretty good. Should I submit a pull request with what I've made?

**Comment by TJScalzo** [comment]
I've done an interesting thing where the cursor doesn't become ![Mac Pointer](http://tobiasahlin.com/static/cursors/pointer.png) until it's hovering over the actual triangle. The styling for that is:
```CSS
a.github-corner {
  cursor:default;
}
.octo-triangle, .octo-arm, .octo-body {
  cursor:pointer;
}
```
I'll create a pull request so you can decide if you like how it looks.
